### ISSUE TITLE
Halt BIFs

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#155]
These halt the entire VM, so not needed for WASM on the Web, but needed for other targets and WASM outside the web potentially.

- [ ] `halt/0`
- [ ] `halt/1`
- [ ] `halt/2`

**Comment by KronicDeth** [comment]
`erlang:halt/1` is called in `erts/preloaded/src/erl_init.erl`.

**Comment by bitwalker** [comment]
These have been implemented
