### ISSUE TITLE
NIF BIFs

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#171]
We hopefully can avoid these completely because any NIFs would be AOT compiled in.

- [x] `load_nif/2` (https://github.com/lumen/lumen/pull/665)
- [x] `nif_error/1` (https://github.com/lumen/lumen/pull/665)
- [x] `nif_error/2`

**Comment by bitwalker** [comment]
This is implemented, but NIF loading is a no-op currently.
