### ISSUE TITLE
Separate or relabel HeapBin and ProcBin proptests in lumen_runtime

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#199]
The strategies for heap binaries pre-date the `ProcBin` implementation, so they generate byte sequences that can be > 64 bytes, the cut-off for `ProcBin` and so the "heap binary" tests are actually testing `HeapBin` and `ProcBin`.

One of two things should happen:
* Separate out the strategies and have separate tests for heap and process binaries to isolate bugs to the `HeapBin` and `ProcBin`
* Rename the heap binary strategies and tests to be "aligned binary" tests to match the `AlignedBinary` trait used for `HeapBin` and `ProcBin`.

**Comment by bitwalker** [comment]
We no longer have separate types for heap and refc binaries, only the pointer type differs - closing this for now.
