### ISSUE TITLE
Lower CPU usage when waiting for timers

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#488]
We might need to add some sleeps if everything is waiting and all we're doing is checking for signals in the outer scheduler loop.  A simple `receive` with no `after` spikes the CPU to 100%

## `init.erl`

```erlang
-module(init).
-export([start/0]).

start() ->
  receive
    Message -> Message
  end,
  ok.
```

**Comment by bitwalker** [comment]
The management of signals and receives has been completely reimplemented, and no longer uses busy looping to wait for things.
