### ISSUE TITLE
Type mismatch for bb argument

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#601]
Errors of the form `type mismatch for argument #N of success #M` for some `N` and `M`.

Affects the following files in OTP:

* `erts/preloaded/src/erts_literal_area_collector.erl`
* `lib/asn1/src/asn1ct_gen_per.erl`
* `lib/asn1/src/asn1ct_pretty_format.erl`
* `lib/asn1/src/asn1ct_table.erl`
* `lib/asn1/src/prepare_templates.erl`
* `lib/common_test/src/ct_slave.erl`
* `lib/compiler/src/beam_listing.erl`
* `lib/compiler/src/beam_peep.erl`
* `lib/compiler/src/beam_ssa_lint.erl`
* `lib/compiler/src/cerl_clauses.erl`
* `lib/compiler/src/beam_trim.erl`
* `lib/debugger/src/dbg_wx_break.erl`
* `lib/debugger/src/debugger.erl`
* `lib/dialyzer/src/dialyzer_clean_core.erl`
* `lib/dialyzer/src/dialyzer_worker.erl`
* `lib/erl_docgen/src/docgen_xmerl_xml_cb.erl`
* `lib/edoc/src/edoc_wiki.erl`
* `lib/eunit/src/eunit_autoexport.erl`
* `lib/inets/src/http_server/httpd_manager.erl`
* `lib/inets/src/http_server/mod_auth_mnesia.erl`
* `lib/kernel/src/erl_compile_server.erl`
* `lib/kernel/src/inet6_tcp.erl`
* `lib/kernel/src/inet6_tcp_dist.erl`
* `lib/kernel/src/inet_hosts.erl`
* `lib/kernel/src/inet_tcp.erl`
* `lib/kernel/src/local_udp.erl`
* `lib/kernel/src/local_tcp.erl`
* `lib/megaco/src/engine/megaco_digit_map.erl`
* `lib/sasl/src/sasl_report_tty_h.erl`
* `lib/sasl/src/sasl_report_file_h.erl`
* `lib/sasl/src/systools_relup.erl`
* `lib/stdlib/src/erl_abstract_code.erl`
* `lib/stdlib/src/error_logger_tty_h.erl`
* `otp/lib/stdlib/src/gb_sets.erl`
* `otp/lib/stdlib/src/io_lib_fread.erl`
* `lib/stdlib/src/sets.erl`

**Comment by bcardarella** [comment]
Per @bitwalker, should be fixed in many places but not 100%.

**Comment by bitwalker** [comment]
No longer applicable/addressed in new compiler
