### ISSUE TITLE
Expected value, but got pseudo-value

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#602]
```
expected value, but got pseudo-value, compiler/codegen/src/builder/function.rs:1276:21
```

Affects the following files in OTP:

* `erts/preloaded/src/prim_buffer.erl`
* `lib/common_test/src/ct_repeat.erl`
* `lib/common_test/src/ct_telnet_client.erl`
* `lib/compiler/src/beam_ssa_pp.erl`
* `lib/kernel/src/raw_file_io_compressed.erl`

**Comment by bcardarella** [comment]
Per @bitwalker, should be fixed in many places but not 100%.

**Comment by bitwalker** [comment]
No longer applicable/fixed by new compiler
