### ISSUE TITLE
Cannot parse multi-line record module attribute

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#604]
At https://github.com/lumen/otp/blob/ca83f680aab717fe65634247d16f18a8cbfc6d8d/lib/kernel/include/inet_sctp.hrl#L197-L208, the fields are separate lines after the name of the record:

![Screen Shot 2020-09-21 at 3 25 55 PM](https://user-images.githubusercontent.com/298259/93817568-c99dc580-fc1e-11ea-8a09-4c741b3ca383.png)
![Screen Shot 2020-09-21 at 3 26 03 PM](https://user-images.githubusercontent.com/298259/93817571-c99dc580-fc1e-11ea-98ea-f230306cdda7.png)

**Comment by KronicDeth** [comment]
Maybe related to #598

**Comment by bcardarella** [comment]
Per Dec 9 standup, @hansihe will review
