### ISSUE TITLE
The given value is not a known block

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#609]
```
stderr:    Compiling /Users/runner/work/lumen/otp/lib/asn1/src/asn1ct_name.erl
 thread '<unnamed>' panicked at 'the given value is not a known block: value544 (Argument(block268, 0))', compiler/codegen/src/builder/function.rs:567:9
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

* `lib/asn1/src/asn1ct_name.erl`
* `lib/asn1/src/asn1rtt_ext.erl`
* `lib/compiler/src/beam_digraph.erl`
* `lib/compiler/src/beam_ssa_recv.erl`
* `lib/compiler/src/beam_ssa_dead.erl`
* `lib/compiler/src/beam_utils.erl`
* `lib/compiler/src/cerl_sets.erl`
* `lib/debugger/src/dbg_wx_mon.erl`
* `lib/inets/src/http_server/httpd_socket.erl`
* `lib/kernel/src/application_master.erl`
* `lib/kernel/src/kernel_config.erl`
* `lib/mnesia/src/mnesia_registry.erl`
* `lib/stdlib/src/erl_expand_records.erl`
* `lib/stdlib/src/maps.erl`
* `lib/stdlib/src/proplists.erl`
* `lib/stdlib/src/timer.erl`

**Comment by bitwalker** [comment]
No longer applicable/fixed in new compiler
