### ISSUE TITLE
Expr::BinaryGenerator is unimplemented for comprehensions

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#611]
```
panicked at 'not implemented', /Users/runner/.cargo/git/checkouts/eir-9a91440c84f5797a/520fc3d/libeir_syntax_erl/src/lower/expr/comprehension.rs:130:44
```

is because [Expr::BinaryGenerator is unimplemented for comprehensions](https://github.com/eirproject/eir/blob/lumen/libeir_syntax_erl/src/lower/expr/comprehension.rs#L130)

Affects the following files in OTP:

* `lib/asn1/src/asn1ct_constructed_per.erl`
* `lib/asn1/src/asn1ct_gen.erl`
* `lib/asn1/src/asn1rtt_ber.erl`
* `lib/asn1/src/asn1rtt_per_common.erl`
* `lib/diameter/src/base/diameter_types.erl`

**Comment by bcardarella** [comment]
Per Dec 9 standup, is still WIP for @hansihe

**Comment by bitwalker** [comment]
This was resolved in the compiler rewrite
