### ISSUE TITLE
Support  _=Expr initializer for records

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#613]
> If several fields are to be assigned the same value, the following construction can be used:
>
> ```
> #Name{Field1=Expr1,...,FieldK=ExprK, _=ExprL}
>
> Omitted fields then get the value of evaluating ExprL instead of their default values. This feature is primarily intended to be > used to create patterns for ETS and Mnesia match functions.

This is not implemented in EIR:

```
stderr:    Compiling /Users/runner/work/lumen/otp/lib/common_test/src/ct_config.erl
error: unrecognized token
    ┌─ /Users/runner/work/lumen/otp/lib/common_test/src/ct_config.erl:301:19
    │
301 │                      config=File,_='_'}),
    │                                  ^ expected: "atom"

error: parsing failed

      Failed /Users/runner/work/lumen/otp/lib/common_test/src/ct_config.erl
```

Affects the following files in OTP: 

* `lib/common_test/src/ct_config.erl`
* `lib/common_test/src/ct_util.erl`
* `lib/common_test/src/ct_util.erl`

**Comment by bcardarella** [comment]
Per Dec 9 standup, @hansihe will check to see if this is resolved or not
