### ISSUE TITLE
Krustlet Provider

### ISSUE THREAD

**Issue by sleipnir** [GetFirefly/firefly#695]
Krustlet acts as a Kubelet by listening on the event stream for new pods that the scheduler assigns to it based on specific Kubernetes tolerations.
The default implementation of Krustlet listens for the architecture wasm32-wasi and schedules those workloads to run in a wasmtime-based runtime instead of a container runtime.

I would like to know if it is possible to use Lumem as a Provider for Krustlet, that way it would be possible to compile elixir programs for Wasm and run these applications on Kubernetes without containers.

What would it take for this to be possible?

**Comment by bitwalker** [comment]
In theory all it should require is the ability to compile to wasm32-wasi as a target, which is what our wasm support needs to target anyway. Beyond that, it would probably be necessary to implement bindings to the host-provided APIs as a NIF, but I haven't looked into what all is offered or required to support there.

Support for this kind of thing is down the road a way yet, we're focusing on full support for native targets first (x86_64/arm64), then fleshing out the wasm32 support once we know the full set of things required to bootstrap a native Erlang/Elixir executable on such a restricted target. But per your question, aside from the ability to target wasm32, I don't think there is any other restrictions on using a Firefly-compiled executable as a krustlet provider.

**Comment by sleipnir** [comment]
Thank you @bitwalker for your answer
