### ISSUE TITLE
Write page explaining change from lumen to firefly.

### ISSUE THREAD

**Issue by fire** [GetFirefly/firefly#712]
Please write a short description of the name change.

**Comment by bitwalker** [comment]
@fire Anything in particular you would like to see explained? I can add a note in the README about the name change, but if there are specific questions you have, that will help give me an idea what people want to know about it.

**Comment by fire** [comment]
Begin with a note of the name change.

IF you want you can add reasons why, and how to for example keep the firefly project running.

**Comment by lpil** [comment]
> A big reason is that over the past year or two we've come across numerous other "Lumen" projects/products, to the point where it started to feel a bit ridiculous. Lumen was picked by me on a whim as a name back when the project started, but it was really meant to be a placeholder, and it just kinda became the formal name of the project since we couldn't come up with anything we liked better at the time. We figured it was best to rename now, before we make any effort to re-stoke interest in the project, and pick something we liked better. I was watching fireflies in my yard this summer, and that was basically the inspiration for the new name, and at the same time I was finishing a rewrite of the entire compiler and core parts of the runtime started earlier this year when I came back to DockYard, so in many ways its not the same project that it was 2 years ago, and a rename feels appropriate for that reason as well.
>
> Anyway, that's probably more detail than you really care about, but now you know the gritty details :)

https://github.com/GetFirefly/firefly/commit/b896336ae101561c6dcaeeb9947a05787409fcac#commitcomment-82504937
