### ISSUE TITLE
Build errors ^^^^^^^^ use of unstable library feature 'core_c_str'

### ISSUE THREAD

**Issue by adjivas** [GetFirefly/firefly#714]
Hello,

I tested the last commit [fd94434](https://github.com/GetFirefly/firefly/commit/fd944344297bf961fac2ec4dddf57e60f9776459)
I get that error on the [Building Firefly](https://github.com/GetFirefly/firefly#building-firefly)' step.
```bash
error[E0658]: use of unstable library feature 'core_c_str'
   --> library/rt/src/term/atom/mod.rs:127:13
    |
127 |         use core::ffi::CStr;
    |             ^^^^^^^^^^^^^^^
    |
    = note: see issue #94079 <https://github.com/rust-lang/rust/issues/94079> for more information
    = help: add `#![feature(core_c_str)]` to the crate attributes to enable
```

Do I forget anything?

That is my full [log](https://gist.github.com/adjivas/a6c7d4af65d199685d5ab000b9a6c20a),
And that is my Dockerfile:
```dockerfile
FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive

RUN useradd -ms /bin/bash user

RUN apt-get update && apt-get install -y build-essential vim git wget curl chrpath file python3

WORKDIR "/root"

# install nightly-2022-07-12 toolchain only
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain nightly-2022-07-12 -y

ENV PATH=/root/.cargo/bin:$PATH

RUN rustup default nightly-2022-07-12

ENV CARGO_MAKE_TOOLCHAIN=nightly-2022-07-12

RUN cargo install cargo-make

RUN rustup target add wasm32-unknown-unknown --toolchain nightly-2022-07-12


RUN apt-get update && apt-get install -y ninja-build cmake ccache

# LLVM
ENV XDG_DATA_HOME=/root/.local/share
RUN mkdir -p $XDG_DATA_HOME/llvm/firefly/ && \
    cd $XDG_DATA_HOME/llvm/firefly/ && \
    wget https://github.com/getfirefly/llvm-project/releases/download/firefly-15.0.0-dev_2022-08-27/clang+llvm-15.0.0-x86_64-linux-gnu.tar.gz && \
    tar -xz --strip-components 1 -f clang+llvm-15.0.0-x86_64-linux-gnu.tar.gz && \
    rm clang+llvm-15.0.0-x86_64-linux-gnu.tar.gz && \
    cd -

# LLVM Project
RUN git clone --depth 1 https://github.com/lumen/llvm-project
RUN cd /root/llvm-project && \
    git checkout firefly && \
    make llvm-shared -C /root/llvm-project && \
    cd -

# FireFly
ENV LLVM_PREFIX=$XDG_DATA_HOME/llvm/firefly
ENV FIREFLY_BUILD_TYPE=static
RUN git clone https://github.com/GetFirefly/firefly.git
RUN cd /root/firefly && cargo make firefly
```

**Comment by bitwalker** [comment]
There's probably two things here (and I'll have to update the README):

1. You need a newer nightly than 2022-07-12, our CI is now using 2022-08-08
2. You'll want to make sure clang is used to compile the project, so make sure you set `CC=/path/to/untarred/clang CXX=/path/to/untarred/clang++` when running `cargo make firefly`

As an aside, I see you added the `wasm32-unknown-unknown` toolchain, but just as a heads up - our runtime isn't compatible with wasm32 just yet (this is coming soon, but our current runtime is tailored for compiler development on AArch64/x86_64, and is not only barebones, but uses an implementation of stack switching that isn't portable to wasm32). I just finished work on the compiler this week, so all of this is being addressed in my next round of work, but just wanted to make sure expectations are set :)

**Comment by bitwalker** [comment]
I've updated the readme to address the outdated toolchain, and make a note about the CC/CXX env vars on Linux. Please reopen this issue if you are still having a problem though!
