### ISSUE TITLE
Compiler will get segmentation fault for some kinds of `when` clauses on function

### ISSUE THREAD

**Issue by tatsuya6502** [GetFirefly/firefly#720]
The following valid Erlang code will cause the Firefly compiler to get segmentation fault:

```erlang
-module(init).
-export([boot/1]).

boot(_Args) -> ok.

a(X) when X rem 10 == 0 ->
    ok.

b(Y) when Y div 10 > 2 ->
    ok.
```

```console
$ firefly compile -C no_default_init --bin init.erl
   Compiling init.erl
zsh: segmentation fault  firefly compile -C no_default_init --bin init.erl
```

**Environment**

- Firefly: develop branch, commit: [323e0ca6](https://github.com/GetFirefly/firefly/commit/323e0ca655df2b7cb70e9be4eeb3cee62d4c486c) (Sep 12, 2022 UTC)
- macOS Monterey 12.6 (arm64)
- Rust: nightly-2022-08-08
- LLVM: firefly-15.0.0-dev_2022-08-27/clang+llvm-15.0.0-arm64-apple-darwin21.6.0.tar.gz

**Comment by bitwalker** [comment]
Fixed in develop
