### ISSUE TITLE
Error running example module on M1

### ISSUE THREAD

**Issue by leostera** [GetFirefly/firefly#723]
Hello! I'm on a M1 Mac, running macOS Monterrey 12.5, using the 0.1.0-nightly-2020-09-02 release.

When trying to run the example:

```erlang
-module(foo).
-behaviour(application).
-export([start/2]).

start(_, _) ->
    erlang:display("hello"),
    bar:start_link().
    
stop(_) -> ok.
```

Compiling it with `firefly compile` (no flags), fails with:

```sh
Assertion failed: (impl && "isa<> used on a null type."), function isa,
  file /Users/paulschoenfelder/src/github.com/bitwalker/llvm-project/mlir/include/mlir/IR/Types.h, line 292.
```

I tried first other Erlang code that had the same assertion failure, and started reducing this down to:

```erlang
-module(foo).
```

This gives me the exact same error. Anyway I can give more info to help?

**Comment by bitwalker** [comment]
Sorry, I'll remove that old release, it is waaaaay out of date, and precedes all of the work done in the past two years, it shouldn't be used.

For now, you have to build the compiler following the instructions in the README, and use that. I'll be producing actual releases in the near future though, so you may just want to wait for those.
